### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by VladHurma** [stimulus-components/stimulus-sortable#30]
I have a project that uses Rails6, that was moved from turbolinks to hotwire just a few month ago.
After the setup of sortable component via official guide(yarn) got following issue in js console:
```
TypeError: Super expression must either be null or a function
    at _inherits (stimulus-sortable.mjs:18:1)
    at stimulus-sortable.mjs:28:1
    at ./node_modules/stimulus-sortable/dist/stimulus-sortable.mjs (stimulus-sortable.mjs:94:1)
    at __webpack_require__ (bootstrap:63:1)
```

application.js:
```
import { Application } from "stimulus"
import Sortable from 'stimulus-sortable'
import { definitionsFromContext } from "stimulus/webpack-helpers"

const application = Application.start()
application.register('sortable', Sortable)

const context = require.context("../controllers", true, /\.js$/)
application.load(definitionsFromContext(context))
```
View:
```
%ul(data-controller="sortable")
  -@user.items.each do |item|
    %li
      =item.title
```

**Comment by guillaumebriday** [comment]
Could you reopen this issue into the main repo https://github.com/stimulus-components/stimulus-components? Thanks!!
